controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    prefix: /
    name_prefix: front_

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    prefix: /admin
    name_prefix: back_

controllers:
    resource: ../src/Controller
    type: attribute
